sudo: false

language: android
jdk: oraclejdk8
notifications:
  email: false

before_install:
- chmod +x gradlew

env:
  global:
  - ANDROID_API_LEVEL=23
  - ANDROID_BUILD_TOOLS_VERSION=23.0.3
  - ANDROID_EMU_API_LEVEL=22
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=5 # minutes (2 minutes by default)
  - QEMU_AUDIO_DRV=none # Remove audio

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMU_API_LEVEL
  - extra-android-support
  - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"

after_success:
- sh set_tags.sh

notifications:
  email: true

deploy:
  provider: releases
  api_key:
    secure: wy43X9WESaODgKXr/ccu8OneJQzqrzy84XZcZ1KA74HN2oZzm+NAZbm1FcrzUBbyvtDWMtV8TDArsYSs4SpMMpeSdJbTkK/IMhhFZxvyQ4XBM6YEdkCKnIuLFuFTgIicHlvtbujClOLX0n+dyAKhFyXBH2N53QurmeqlLaYcMXJCdhtnNw7H+8jB/BOvhlR1j5OpG4gQQjio+1YTNGvKu6b0l8yYcLR3i0+YLVhIozwbet12GXrY/nvJAd5fwKe5hqHpGqMIVEqtSBIA+nfijPOYclHal7D3BfRP77jO/dklkAOygLxEzZQiVkfTIWREBbOsllj5bivCbZUmKhQc1lo/Wp+XPC+AO8mnBVOfYHW9l62e+pVieGDdbAdKw7vPIXBHmw2QTSbboRnQMHqU+tNXb2BmZkJGtZaHDwoPZ6xjsbxctSCpm8mn+VV1uOSBp7mHx4iXXqW+Q5YiQ2d5I3fdiAko54g4hT40KIYfSpE4022kzF42BU3apzCnpRhQnAvJid3KEdUAXANXkSxo00WC0lEx2LzxDKzNrheEmPb/uXAQa3OwpKgMP/yI1mrZ0IvAAc9q6NNxHJPeKil6yVQRLexGs3QqjAEwbN4pw1mq1V4zzoBi3Vxb9czKl6iAmVYvF1OY+ZqBHJTBdCHiTiOEbDZVG5yr7j+8VGL/lJw=
  file: autodeployapp/build/outputs/apk/autodeployapp*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: zsavely/AutoDeployExample


before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
